name: GitHub City

on:
  schedule:
    - cron: '0 */4 * * *' # 每4小时执行一次
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 生成 skyline city metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.city.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
          output_action: none

      - name: 推送 skyline city metrics 到 github_city 分支
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: github_city
          build_dir: metrics_renders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
