name: Update Lang Box Stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update-lang-box-stats
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: f12b1909e28c47d7343c80b9590fe61c
      USERNAME: ${{ secrets.USERNAME }}
      DAYS: 14
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: profile/README.md
      LANGBOX_BLOCK_START: <!-- lang-box start -->
      LANGBOX_BLOCK_END: <!-- lang-box end -->
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go
      - name: Check out profile repo
        uses: actions/checkout@v2
        with:
          path: profile
      - name: Install Ruby and github-linguist
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev git make gcc
          sudo gem install github-linguist
      - name: Check github-linguist version
        run: github-linguist --version
      - name: Clone and build lang-box-go
        run: |
          git clone https://github.com/Viper373/lang-box-go.git
          cd lang-box-go && go build -o langbox main.go
          mv ./langbox ../ && cd .. && rm -rf lang-box-go/
      - name: Run lang-box
        run: ./langbox
      - name: Commit and push
        run: |
          cd profile
          git config --global user.email "bot@github.com"
          git config --global user.name "LangBox-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull --rebase && git push
      
