name: Update NetEase-music-box
on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 16 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Update gist
        uses: ./
        env:
          TIMEZONE: Asia/Shanghai
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NETEASE_GIST_ID: 0de3f9fc7f3078a800f738e25eccea54
          NETEASE_USER_ID: ${{ secrets.NETEASE_USER_ID }}
          NETEASE_USER_TOKEN: ${{ secrets.NETEASE_USER_TOKEN }}
          MARKDOWN_FILE: README.md
      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Netease-music-Bot"
          git diff
          git add README.md && git commit -m ":robot: Github Action schedule automatically" || exit 0
          git pull --rebase && git push
