name: github_snk

on:
  # 每天UTC时间8点自动运行
  schedule:
    - cron: "0 8 * * *" 

  # 允许手动触发
  workflow_dispatch:

  # 当推送到main分支时触发
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 生成GitHub贡献图的蛇形动画SVG文件
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 将生成的SVG文件推送到snk_output分支
      - name: push github-contribution-grid-snake.svg to snk_output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snk_output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
